# Site settings
title: "JC's collection of tech and electronics"
tagline: ""
description: ""

email: jwoltz@gmail.com
url: 	"//jcwoltz.github.io" # the base hostname & protocol for your site
#url:     "//localhost:4000"
baseurl: ""
paginate: 5

# Build settings
markdown: kramdown
highlighter: pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:year/:month/:day/:title/
#relative_permalinks: true

timezone: America/New_York

author:
  name: JC Woltz
  email: jwoltz@gmail.com
  github: jcwoltz

github_username:  jcwoltz

# Exclude Ruby gem stuff
exclude: ["vendor"]
